#!/bin/bash

parse_domains() {
    # For each configuration file in /etc/nginx/conf.d/*.conf*
    for conf_file in /etc/nginx/conf.d/*.conf*; do
        sed -n -e 's&^\s*ssl_certificate_key\s*\/etc/letsencrypt/live/\(.*\)/privkey.pem;&\1&p' $conf_file | xargs echo
    done
}

is_renewal_required() {
    # If the file does not exist assume a renewal is required
    last_renewal_file="/etc/letsencrypt/live/$1/privkey.pem"
    [ ! -e "$last_renewal_file" ] && return;
    
    # If the file exists, check if the last renewal was more than a week ago
    one_week_sec=604800
    now_sec=$(date -d now +%s)
    last_renewal_sec=$(stat -c %Y "$last_renewal_file")
    last_renewal_delta_sec=$(( ($now_sec - $last_renewal_sec) ))
    is_finshed_week_sec=$(( ($one_week_sec - $last_renewal_delta_sec) ))
    [ $is_finshed_week_sec -lt 0 ]
}
get_certificate() {
    echo "running certbot ... $1 $2"
    certbot certonly --webroot --webroot-path /etc/letsencrypt/webrootauth -d $1 --email $2 --agree-tos --quiet --renew-by-default
    chmod +x /etc/letsencrypt/archive
}

# Lets Encrypt
if [ -z "$EMAIL" ]; then
    echo "You need the \$EMAIL Variable"
else

    for domain in $(parse_domains); do
        if is_renewal_required $domain; then
            # Renewal required for this doman.
            # Last one happened over a week ago (or never)
            if ! get_certificate $domain $EMAIL; then
                error "Cerbot failed for $domain. Check the logs for details."
                exit_code=1
            fi
        else
            echo "Not run certbot for $domain; last renewal happened just recently."
        fi
    done
    nginx -s reload 

fi

